### PR TITLE
Added retrieve path, see #35 for more info

### PR DESCRIPTION
**Pull request by younes0**
#35

### CODE REVIEW

**Comment by younes0** [comment]
My apologies, I didn't see your question.
I'll check the filepath_callback soon

**Comment by younes0** [comment]
the set_filepath_callback works fine, what a shame that I missed it 
`
Casset::set_filepath_callback(function($filepath, $type, $remote) {
     return str_replace('temp/', '', $filepath);
});
`

**Comment by canton7** [comment]
Sweet! While your request is perfectly valid, the way that Casset's grown means it's rather hard to implement at this stage. If Casset ever gets a re-write, this will be in there.

**Comment by younes0** [comment]
I understand, cheers

**Pull request closed without merging**
